// Google Test suite generated by Claude Sonnet 5
//
// Note: Modified by author (Maachue)

// Google Test suite for:
//   dumbutf::charWidth(uint32_t CP)       -> 0, 1, or 2 terminal cells
//   dumbutf::ambiguousWidth(uint32_t CP)  -> bool (UAX #11 category "A")
//
// Reference: Unicode Standard 17.0.0 / UAX #11 (East Asian Width)

#include "dumbutf/charwidth.hpp"

#include "utf8proc.h"
#include "gtest/gtest.h"

#include "Msg.h"

#include <cstdint>
#include <string>

// ---------------------------------------------------------------------
// charWidth() tests
// ---------------------------------------------------------------------

struct CharWidthCase {
  uint32_t cp;
  int expectedWidth;
  const char *description;
};

class CharWidthTest : public ::testing::TestWithParam<CharWidthCase> {};

TEST_P(CharWidthTest, ReturnsExpectedWidth) {
  const auto &c = GetParam();
  EXPECT_EQ(dumbutf::codepointCharWidth(c.cp), c.expectedWidth)
      << CPMessage(c.cp) << " (" << c.description << ")";
}

// --- Width 0: control chars, combining marks, zero-width formatting ---
INSTANTIATE_TEST_SUITE_P(
    ZeroWidth, CharWidthTest,
    ::testing::Values(
        CharWidthCase{0x0000, 0, "NULL"},
        CharWidthCase{0x0007, 0, "BELL (control)"},
        CharWidthCase{0x001B, 0, "ESCAPE (control)"},
        CharWidthCase{0x0300, 0, "COMBINING GRAVE ACCENT (Mn, EAW=A)"},
        CharWidthCase{0x0301, 0, "COMBINING ACUTE ACCENT (Mn)"},
        CharWidthCase{0x0483, 0, "COMBINING CYRILLIC TITLO (Mn)"},
        CharWidthCase{0x1AB0, 0, "COMBINING DOUBLED CIRCUMFLEX ACCENT (Mn)"},
        CharWidthCase{0x200B, 0, "ZERO WIDTH SPACE"},
        CharWidthCase{0x200D, 0, "ZERO WIDTH JOINER"},
        CharWidthCase{0xFE0F, 0, "VARIATION SELECTOR-16"}
        // CharWidthCase{0x1F3FB, 0, "EMOJI MODIFIER FITZPATRICK TYPE-1-2"}
        ));

// --- Width 1: normal narrow / halfwidth / neutral characters ---
INSTANTIATE_TEST_SUITE_P(
    NarrowWidth, CharWidthTest,
    ::testing::Values(
        CharWidthCase{0x0020, 1, "SPACE"},
        CharWidthCase{0x0030, 1, "DIGIT ZERO"},
        CharWidthCase{0x0041, 1, "LATIN CAPITAL LETTER A"},
        CharWidthCase{0x0061, 1, "LATIN SMALL LETTER A"},
        CharWidthCase{0x00A5, 1, "YEN SIGN (Na)"},
        CharWidthCase{0x00AF, 1, "MACRON (Na)"},
        CharWidthCase{0xFF61, 1, "HALFWIDTH IDEOGRAPHIC FULL STOP (H)"},
        CharWidthCase{0xFF9F, 1,
                      "HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK (H)"}));

// --- Ambiguous-category characters: charWidth() must treat them as 1 ---

INSTANTIATE_TEST_SUITE_P(
    AmbiguousTreatedAsNarrow, CharWidthTest,
    ::testing::Values(
        CharWidthCase{0x00A1, 1, "INVERTED EXCLAMATION MARK (A)"},
        CharWidthCase{0x00AD, 1, "SOFT HYPHEN"},
        CharWidthCase{0x00A4, 1, "CURRENCY SIGN (A)"},
        CharWidthCase{0x00A7, 1, "SECTION SIGN (A)"},
        CharWidthCase{0x0391, 1, "GREEK CAPITAL LETTER ALPHA (A)"},
        CharWidthCase{0x0410, 1, "CYRILLIC CAPITAL LETTER A (A)"},
        CharWidthCase{0x2018, 1, "LEFT SINGLE QUOTATION MARK (A)"},
        CharWidthCase{0x2019, 1, "RIGHT SINGLE QUOTATION MARK (A)"},
        CharWidthCase{0x2500, 1, "BOX DRAWINGS LIGHT HORIZONTAL (A)"},
        CharWidthCase{0x25A0, 1, "BLACK SQUARE (A)"}));

// --- Width 2: wide / fullwidth characters ---
INSTANTIATE_TEST_SUITE_P(
    WideWidth, CharWidthTest,
    ::testing::Values(
        CharWidthCase{0x2E80, 2, "CJK RADICAL REPEAT (W)"},
        CharWidthCase{0x3000, 2, "IDEOGRAPHIC SPACE (F)"},
        CharWidthCase{0x3042, 2, "HIRAGANA LETTER A (W)"},
        CharWidthCase{0x4E00, 2, "CJK UNIFIED IDEOGRAPH-4E00 (W)"},
        CharWidthCase{0xAC00, 2, "HANGUL SYLLABLE GA (W)"},
        CharWidthCase{0xFF21, 2, "FULLWIDTH LATIN CAPITAL LETTER A (F)"},
        CharWidthCase{0x1F600, 2, "GRINNING FACE EMOJI (W)"},
        CharWidthCase{0x20000, 2,
                      "CJK UNIFIED IDEOGRAPH-20000, plane 2 (W) "}));

// ---------------------------------------------------------------------
// ambiguousWidth() tests
// ---------------------------------------------------------------------

struct AmbiguousCase {
  uint32_t cp;
  bool expectedAmbiguous;
  const char *description;
};

class AmbiguousWidthTest : public ::testing::TestWithParam<AmbiguousCase> {};

TEST_P(AmbiguousWidthTest, ReturnsExpectedAmbiguity) {
  const auto &c = GetParam();
  EXPECT_EQ(dumbutf::isAmbiguousWidth(c.cp), c.expectedAmbiguous)
      << CPMessage(c.cp) << " (" << c.description << ")";
}

// --- Codepoints whose UAX #11 East Asian Width category is "A" ---
INSTANTIATE_TEST_SUITE_P(
    Ambiguous, AmbiguousWidthTest,
    ::testing::Values(
        AmbiguousCase{0x00A1, true, "INVERTED EXCLAMATION MARK"},
        AmbiguousCase{0x00A4, true, "CURRENCY SIGN"},
        AmbiguousCase{0x00A7, true, "SECTION SIGN"},
        AmbiguousCase{0x0391, true, "GREEK CAPITAL LETTER ALPHA"},
        AmbiguousCase{0x0410, true, "CYRILLIC CAPITAL LETTER A"},
        AmbiguousCase{0x2018, true, "LEFT SINGLE QUOTATION MARK"},
        AmbiguousCase{0x2019, true, "RIGHT SINGLE QUOTATION MARK"},
        AmbiguousCase{0x2500, true, "BOX DRAWINGS LIGHT HORIZONTAL"},
        AmbiguousCase{0x25A0, true, "BLACK SQUARE"},
        AmbiguousCase{0x00AD, true, "SOFT HYPHEN"},
        // Special case: category A despite being a zero-width combining
        // mark when actually rendered (general category Mn).
        AmbiguousCase{
            0x0300, true,
            "COMBINING GRAVE ACCENT (EAW=A; Mn -> renders as 0 width)"}));

// --- Codepoints that are NOT ambiguous (Narrow, Wide, Fullwidth, Halfwidth,
// Neutral) ---
INSTANTIATE_TEST_SUITE_P(
    NotAmbiguous, AmbiguousWidthTest,
    ::testing::Values(
        AmbiguousCase{0x0000, false, "NULL (control, Neutral)"},
        AmbiguousCase{0x0041, false, "LATIN CAPITAL LETTER A (Na)"},
        AmbiguousCase{0x200B, false, "ZERO WIDTH SPACE (Neutral)"},
        AmbiguousCase{0x4E00, false, "CJK UNIFIED IDEOGRAPH-4E00 (W)"},
        AmbiguousCase{0xAC00, false, "HANGUL SYLLABLE GA (W)"},
        AmbiguousCase{0xFF21, false, "FULLWIDTH LATIN CAPITAL LETTER A (F)"},
        AmbiguousCase{0xFF61, false, "HALFWIDTH IDEOGRAPHIC FULL STOP (H)"},
        AmbiguousCase{0x1F600, false, "GRINNING FACE EMOJI (W)"}));

#ifdef DUMBUTF_TESTS_FULL
TEST(CharWidthTest, AllCPs) {
  for (uint32_t CP = 0; CP <= 0x10FFFF; ++CP) {
    if (!utf8proc_codepoint_valid(static_cast<utf8proc_int32_t>(CP))) {
      continue;
    }

    auto dumbutf_Res = dumbutf::codepointCharWidth(CP);
    auto utf8proc_Res = utf8proc_charwidth(static_cast<utf8proc_int32_t>(CP));

    EXPECT_EQ(dumbutf_Res, utf8proc_Res) << CPMessage(CP);
  }
}

TEST(AmbiguousWidthTest, AllCPs) {
  for (uint32_t CP = 0; CP <= 0x10FFFF; ++CP) {
    if (!utf8proc_codepoint_valid(static_cast<utf8proc_int32_t>(CP))) {
      continue;
    }

    EXPECT_EQ(dumbutf::isAmbiguousWidth(CP), utf8proc_charwidth_ambiguous(CP))
        << CPMessage(CP);
  }
}
#endif
