// NOTE: Generated by Claude Sonnet 5 (prompting)

//===========================================================================//
//
// Unit tests for: Convert between UTF.
//
//===========================================================================//

#include "dumbutf/UTF.hpp"

#include "gtest/gtest.h"

#include "Msg.h"

#include <algorithm>
#include <array>
#include <ostream>
#include <span>
#include <string_view>

using namespace dumbutf;

namespace {
struct Convert_UTF8_to_UTF32_Case {
  std::string_view UTF8StringInput;
  std::span<const UTF32> UTF32StringExpected;
  const char *Desc = nullptr;

  friend std::ostream &operator<<(std::ostream &OS,
                                  Convert_UTF8_to_UTF32_Case const &V) {
    OS << "UTF-8 Input: '" << V.UTF8StringInput << "'; UTF-32 Expected: '"
       << CPSPrint(V.UTF32StringExpected) << "'";
    if (V.Desc)
      OS << "; Desc: " << V.Desc;

    return OS;
  }
};
} // namespace

//------------------------------------------------------------------------------
//
// 0. Tests for convert_UTF8_to_UTF32_LOSSLY
//
//------------------------------------------------------------------------------
//
// convert_UTF8_to_UTF32_LOSSLY() repeatedly applies the single-codepoint
// LOSSLY decode step across the whole input buffer, so its error recovery
// inherits the WHATWG Encoding Standard's UTF-8 decoder algorithm
// (https://encoding.spec.whatwg.org/#utf-8-decoder), including its
// "prepend" rule: when a byte fails a continuation-byte check partway
// through a sequence, that byte is put back and reprocessed as the start of
// a brand new decode attempt.
//
// An important, easy-to-miss consequence for convert_*(): a single
// malformed multi-byte sequence can expand into SEVERAL U+FFFD codepoints
// in the output - one for the rejected leading byte, plus one MORE for
// every trailing byte that turns out to be a stray/lone continuation byte
// with no sequence of its own to join. This matches the canonical worked
// examples from the WHATWG spec, e.g.:
//   C0 AF        -> U+FFFD, U+FFFD                    (2 codepoints)
//   E0 9F 80     -> U+FFFD, U+FFFD, U+FFFD             (3 codepoints)
//   ED A0 80     -> U+FFFD, U+FFFD, U+FFFD             (3 codepoints)
//   F0 80 80 80  -> U+FFFD, U+FFFD, U+FFFD, U+FFFD      (4 codepoints)
// By contrast, if the byte that gets prepended happens to be a perfectly
// valid ASCII byte (or the start of a valid new sequence), decoding resumes
// normally from there, so only ONE U+FFFD is produced overall, e.g.
//   E1 41        -> U+FFFD, 'A'                        (2 codepoints)
// and NOT two U+FFFD codepoints.
//
//------------------------------------------------------------------------------

struct Convert_UTF8_to_UTF32_LOSSLY_Test
    : public ::testing::TestWithParam<Convert_UTF8_to_UTF32_Case> {};

TEST_P(Convert_UTF8_to_UTF32_LOSSLY_Test, Convert) {
  auto const &P = GetParam();
  std::array<UTF32, 64> Buffer{};

  ptrdiff_t N = convert_UTF8_to_UTF32_LOSSLY(P.UTF8StringInput, Buffer.data(),
                                             Buffer.size());

  ASSERT_GE(N, 0) << P;
  ASSERT_LE(static_cast<size_t>(N), Buffer.size()) << P;

  std::span<const UTF32> Result(Buffer.data(), static_cast<size_t>(N));

  EXPECT_EQ(Result.size(), P.UTF32StringExpected.size()) << P;
  EXPECT_TRUE(std::equal(Result.begin(), Result.end(),
                         P.UTF32StringExpected.begin(),
                         P.UTF32StringExpected.end()))
      << P;
}

// --- ASCII only (valid, and with a stray invalid byte mixed in) ---
static constexpr UTF32 Expected_AsciiOnly_Hello[] = {'H', 'e', 'l', 'l', 'o'};
static constexpr UTF32 Expected_AsciiOnly_WithInvalidByte[] = {
    'A', 'B', UTF32_REPLACEMENT_CHARACTER, 'C', 'D'};

INSTANTIATE_TEST_SUITE_P(
    AsciiOnly, Convert_UTF8_to_UTF32_LOSSLY_Test,
    ::testing::Values(
        Convert_UTF8_to_UTF32_Case{"Hello", Expected_AsciiOnly_Hello,
                                   "Pure ASCII, all valid"},
        Convert_UTF8_to_UTF32_Case{
            "AB\x80\x43\x44", Expected_AsciiOnly_WithInvalidByte,
            "A stray continuation byte (0x80) mixed into otherwise-ASCII "
            "text becomes its own U+FFFD; surrounding ASCII is unaffected"}));

// --- Two bytes (valid, and invalid) ---
static constexpr UTF32 Expected_TwoBytes_Valid[] = {0x03C0 /* pi */,
                                                    0x00A9 /* copyright */};
static constexpr UTF32 Expected_TwoBytes_Truncated[] = {
    'A', UTF32_REPLACEMENT_CHARACTER};
static constexpr UTF32 Expected_TwoBytes_BadContinuation[] = {
    UTF32_REPLACEMENT_CHARACTER, 'A', 'B'};

INSTANTIATE_TEST_SUITE_P(
    TwoBytes, Convert_UTF8_to_UTF32_LOSSLY_Test,
    ::testing::Values(
        Convert_UTF8_to_UTF32_Case{"\xCF\x80\xC2\xA9", Expected_TwoBytes_Valid,
                                   "PI followed by copyright sign"},
        Convert_UTF8_to_UTF32_Case{
            "A\xC2", Expected_TwoBytes_Truncated,
            "Truncated: leading byte is the last byte in the buffer"},
        Convert_UTF8_to_UTF32_Case{
            "\xC2\x41\x42", Expected_TwoBytes_BadContinuation,
            "Continuation byte is plain ASCII 'A': becomes U+FFFD, then "
            "decoding resumes cleanly at 'A','B'"}));

// --- Three bytes (valid, and invalid) ---
static constexpr UTF32 Expected_ThreeBytes_Valid[] = {0x20AC /* euro */,
                                                      0x2665 /* heart */};
static constexpr UTF32 Expected_ThreeBytes_Truncated[] = {
    'A', UTF32_REPLACEMENT_CHARACTER};
static constexpr UTF32 Expected_ThreeBytes_BadFirstContinuation[] = {
    UTF32_REPLACEMENT_CHARACTER, 'A', 'B'};
static constexpr UTF32 Expected_ThreeBytes_BadSecondContinuation[] = {
    UTF32_REPLACEMENT_CHARACTER, 'A', 'B'};

INSTANTIATE_TEST_SUITE_P(
    ThreeBytes, Convert_UTF8_to_UTF32_LOSSLY_Test,
    ::testing::Values(
        Convert_UTF8_to_UTF32_Case{"\xE2\x82\xAC\xE2\x99\xA5",
                                   Expected_ThreeBytes_Valid,
                                   "Euro sign followed by black heart suit"},
        Convert_UTF8_to_UTF32_Case{
            "A\xE9\x9B", Expected_ThreeBytes_Truncated,
            "Truncated: leading + 1 valid continuation, buffer ends before "
            "the final byte"},
        Convert_UTF8_to_UTF32_Case{
            "\xE1\x41\x42", Expected_ThreeBytes_BadFirstContinuation,
            "First continuation byte is plain ASCII 'A': becomes U+FFFD, "
            "decoding resumes cleanly at 'A','B'"},
        Convert_UTF8_to_UTF32_Case{
            "\xE1\xBA\x41\x42", Expected_ThreeBytes_BadSecondContinuation,
            "Second continuation byte is plain ASCII 'A': becomes U+FFFD, "
            "decoding resumes cleanly at 'A','B'"}));

// --- Four bytes (valid, and invalid) ---
static constexpr UTF32 Expected_FourBytes_Valid[] = {
    0x1F600 /* grinning face */, 0x1F389 /* party popper */};
static constexpr UTF32 Expected_FourBytes_Truncated[] = {
    'A', UTF32_REPLACEMENT_CHARACTER};
static constexpr UTF32 Expected_FourBytes_BadFinalContinuation[] = {
    UTF32_REPLACEMENT_CHARACTER, 'A', 'B'};

INSTANTIATE_TEST_SUITE_P(
    FourBytes, Convert_UTF8_to_UTF32_LOSSLY_Test,
    ::testing::Values(
        Convert_UTF8_to_UTF32_Case{"\xF0\x9F\x98\x80\xF0\x9F\x8E\x89",
                                   Expected_FourBytes_Valid,
                                   "Grinning face followed by party popper"},
        Convert_UTF8_to_UTF32_Case{
            "A\xF0\x9D\x84", Expected_FourBytes_Truncated,
            "Truncated: leading + 2 valid continuations, buffer ends before "
            "the final byte"},
        Convert_UTF8_to_UTF32_Case{
            "\xF0\x9F\x98\x41\x42", Expected_FourBytes_BadFinalContinuation,
            "Final continuation byte is plain ASCII 'A': becomes U+FFFD, "
            "decoding resumes cleanly at 'A','B'"}));

// --- Overlong encodings and surrogate halves ---
//
// These are the canonical worked examples from the WHATWG spec: rejection
// happens on the FIRST continuation byte (narrowed boundary check), so the
// leading byte becomes one U+FFFD, and every remaining byte of the failed
// attempt - being a lone continuation byte with nothing to attach to -
// becomes its own additional U+FFFD.
static constexpr UTF32 Expected_Overlong_2Byte_Slash[] = {
    UTF32_REPLACEMENT_CHARACTER, UTF32_REPLACEMENT_CHARACTER};
static constexpr UTF32 Expected_Overlong_3Byte[] = {
    UTF32_REPLACEMENT_CHARACTER, UTF32_REPLACEMENT_CHARACTER,
    UTF32_REPLACEMENT_CHARACTER};
static constexpr UTF32 Expected_Surrogate_3Byte[] = {
    UTF32_REPLACEMENT_CHARACTER, UTF32_REPLACEMENT_CHARACTER,
    UTF32_REPLACEMENT_CHARACTER};
static constexpr UTF32 Expected_Overlong_Or_OutOfRange_4Byte[] = {
    UTF32_REPLACEMENT_CHARACTER, UTF32_REPLACEMENT_CHARACTER,
    UTF32_REPLACEMENT_CHARACTER, UTF32_REPLACEMENT_CHARACTER};

INSTANTIATE_TEST_SUITE_P(
    OverlongAndSurrogate, Convert_UTF8_to_UTF32_LOSSLY_Test,
    ::testing::Values(
        Convert_UTF8_to_UTF32_Case{
            "\xC0\xAF", Expected_Overlong_2Byte_Slash,
            "Overlong encoding of '/' (classic 2-U+FFFD example)"},
        Convert_UTF8_to_UTF32_Case{
            "\xE0\x9F\x80", Expected_Overlong_3Byte,
            "Overlong 3-byte: 0xE0's continuation must be >= 0xA0"},
        Convert_UTF8_to_UTF32_Case{"\xE0\x80\x80", Expected_Overlong_3Byte,
                                   "Overlong 3-byte encoding of U+0000"},
        Convert_UTF8_to_UTF32_Case{
            "\xED\xA0\x80", Expected_Surrogate_3Byte,
            "Surrogate U+D800: 0xED's continuation must be <= 0x9F"},
        Convert_UTF8_to_UTF32_Case{
            "\xED\xBF\xBF", Expected_Surrogate_3Byte,
            "Surrogate U+DFFF: 0xED's continuation must be <= 0x9F"},
        Convert_UTF8_to_UTF32_Case{
            "\xF0\x80\x80\x80", Expected_Overlong_Or_OutOfRange_4Byte,
            "Overlong 4-byte: 0xF0's continuation must be >= 0x90"},
        Convert_UTF8_to_UTF32_Case{
            "\xF4\x90\x80\x80", Expected_Overlong_Or_OutOfRange_4Byte,
            "Beyond U+10FFFF: 0xF4's continuation must be <= 0x8F"}));

// --- Zero-size UTF-8 input ---
//
// Per the function contract, this must return 0; the contents written to
// UTF32Str are left undefined. Comparing against an empty expected span is
// safe here since std::equal() over a zero-length range never touches the
// (unwritten) buffer.
INSTANTIATE_TEST_SUITE_P(
    ZeroSizeInput, Convert_UTF8_to_UTF32_LOSSLY_Test,
    ::testing::Values(Convert_UTF8_to_UTF32_Case{
        "", {}, "Empty input: returns 0, output buffer contents undefined"}));

// --- Mixed: several kinds combined in one buffer ---
static constexpr UTF32 Expected_Mixed_AllValidTypes[] = {
    'A', 0x00A9 /* copyright */, 0x20AC /* euro */,
    0x1F600 /* grinning face */};
static constexpr UTF32 Expected_Mixed_ValidThenTruncated[] = {
    'A', 0x00A9 /* copyright */, 0x20AC /* euro */, 0x1F600 /* grinning face */,
    UTF32_REPLACEMENT_CHARACTER};
static constexpr UTF32 Expected_Mixed_KitchenSink[] = {
    'H',
    'i',
    ' ',
    0x03C0 /* pi */,
    ' ',
    0x4E2D /* CJK U+4E2D */,
    ' ',
    0x1F600 /* grinning face */,
    ' ',
    UTF32_REPLACEMENT_CHARACTER,
    UTF32_REPLACEMENT_CHARACTER,
    ' ',
    UTF32_REPLACEMENT_CHARACTER,
    UTF32_REPLACEMENT_CHARACTER,
    UTF32_REPLACEMENT_CHARACTER,
    ' ',
    'e',
    'n',
    'd'};

INSTANTIATE_TEST_SUITE_P(
    Mixed, Convert_UTF8_to_UTF32_LOSSLY_Test,
    ::testing::Values(
        Convert_UTF8_to_UTF32_Case{
            "A\xC2\xA9\xE2\x82\xAC\xF0\x9F\x98\x80",
            Expected_Mixed_AllValidTypes,
            "ASCII, then 2-byte, 3-byte and 4-byte sequences back to back, "
            "all valid"},
        Convert_UTF8_to_UTF32_Case{
            "A\xC2\xA9\xE2\x82\xAC\xF0\x9F\x98\x80\xE1",
            Expected_Mixed_ValidThenTruncated,
            "Same as above, plus a truncated 3-byte leading byte at the "
            "very end of the buffer"},
        Convert_UTF8_to_UTF32_Case{
            "Hi \xCF\x80 \xE4\xB8\xAD \xF0\x9F\x98\x80 \xC0\xAF \xED\xA0\x80 "
            "end",
            Expected_Mixed_KitchenSink,
            "Kitchen sink: ASCII text, a 2-byte, a 3-byte and a 4-byte "
            "codepoint, an overlong 2-byte sequence, and an encoded "
            "surrogate, all separated by plain spaces"}));

//------------------------------------------------------------------------------
//
// Destination buffer capacity handling
//
//------------------------------------------------------------------------------

TEST(Convert_UTF8_to_UTF32_LOSSLY_CapacityTest, ExactCapacitySucceeds) {
  static constexpr std::string_view Input = "\xE2\x82\xAC"; // Euro, 1 CP
  std::array<UTF32, 1> Buffer{};

  ptrdiff_t N =
      convert_UTF8_to_UTF32_LOSSLY(Input, Buffer.data(), Buffer.size());

  ASSERT_EQ(N, 1);
  EXPECT_EQ(Buffer[0], static_cast<UTF32>(0x20AC));
}

TEST(Convert_UTF8_to_UTF32_LOSSLY_CapacityTest,
     InsufficientCapacityReturnsNegative) {
  static constexpr std::string_view Input = "\xE2\x82\xAC\xE2\x99\xA5"; // 2 CPs
  std::array<UTF32, 1> Buffer{}; // Only room for 1, but input has 2.

  ptrdiff_t N =
      convert_UTF8_to_UTF32_LOSSLY(Input, Buffer.data(), Buffer.size());

  EXPECT_LT(N, 0) << "Destination buffer is too small to hold every "
                     "decoded codepoint";
}
